Revert r19943: it broke running the node with the wrapper: Exception in thread "main" java.lang.NoClassDefFoundError: freenet/node/NodeStarter
git-svn-id: file:///home/toad/git-migration/temprepository/trunk/freenet@19948 67a373e5-eb02-0410-a15c-ee090a768436