DisconnectedException: Don't synchronize function which modifies nothing; JavaDoc - The synchronized likely resulted from copy-pasting the parent function which does modify stuff as skeleton. - Add JavaDoc which explains the typical reason for not producing a stack trace.