Fix regression by f7692a196ee15b901d90db726e11d46812592eb8
ArrayList->ArrayDeque change triggers run-time exception:
java.lang.ClassCastException: java.util.ArrayDeque cannot be cast to java.util.List