NodeUpdateManager: fix using SSK on Java 6
The NodeUpdateManager requires USKs, so launching a new node on Java 6
failed:

freenet.config.InvalidConfigValueException: Update URI must be a USK!
      at freenet.node.updater.NodeUpdateManager.<init>(NodeUpdateManager.java:255)
      at freenet.node.updater.NodeUpdateManager.maybeCreate(NodeUpdateManager.java:825)
      at freenet.node.Node.<init>(Node.java:1681)
      at freenet.node.NodeStarter.start(NodeStarter.java:194)
      at org.tanukisoftware.wrapper.WrapperManager$11.run(WrapperManager.java:4048)
Failed to load node: 21 : Could not create Updater: freenet.config.InvalidConfigValueException: Update URI must be a USK! (21)
freenet.node.NodeInitException: Could not create Updater: freenet.config.InvalidConfigValueException: Update URI must be a USK! (21)
      at freenet.node.Node.<init>(Node.java:1684)
      at freenet.node.NodeStarter.start(NodeStarter.java:194)
      at org.tanukisoftware.wrapper.WrapperManager$11.run(WrapperManager.java:4048)